name: Ata Karagoz
markdown: kramdown
baseurl: /atakaragoz.github.io
permalink: /blog/:year/:month/:day/:title
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

theme: jekyll-theme-hacker